### ISSUE TITLE
`exec /commento/commento: exec format error` when setting up with docker on raspberry pi 3b+

### ISSUE THREAD

**Issue by sander1095** [souramoo/commentoplusplus#119]
Hello!

I am following this tutorial to set up commento++:

https://noted.lol/commento-a-self-hosted-comment-system-for-websites-that-just-works/

When I use that exact dockerfile (while changing the `COMMENTO_ORIGIN``to my own) and running `docker-compose up`, I get the following logs on my raspberry pi 3b+:.

```
db_1      |
db_1      | PostgreSQL Database directory appears to contain a database; Skipping initialization
server_1  | exec /commento/commento: exec format error
db_1      |
db_1      | 2022-08-19 16:12:41.758 UTC [1] LOG:  starting PostgreSQL 12.5 on arm-unknown-linux-musleabihf, compiled by gcc (Alpine 10.2.1_pre1) 10.2.1 20201203, 32-bit
db_1      | 2022-08-19 16:12:41.758 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1      | 2022-08-19 16:12:41.758 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1      | 2022-08-19 16:12:41.780 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1      | 2022-08-19 16:12:41.871 UTC [21] LOG:  database system was shut down at 2022-08-19 16:11:44 UTC
db_1      | 2022-08-19 16:12:41.893 UTC [1] LOG:  database system is ready to accept connections
commento_server_1 exited with code 1
```

FYI: My dockerfile looks like this:

```
version: '3'

services:
  server:
    image: caroga/commentoplusplus:v1.8.6
    ports:
      - 8080:8080
    environment:
#   I tried both, neither work!
      COMMENTO_ORIGIN: https://commento.mydomain.com
#    COMMENTO_ORIGIN: http://127.0.0.1:8080
      COMMENTO_PORT: 8080
      COMMENTO_POSTGRES: postgres://postgres:postgres@db:5432/commento?sslmode=disable
#    Note: These are copied from the blog post. I want to disable them, but even commenting them out doesn't make the server start.
      COMMENTO_SMTP_HOST: smtp.mailgun.org
      COMMENTO_SMTP_PORT: 587
      COMMENTO_SMTP_USERNAME: mailgun.smtp.user
      COMMENTO_SMTP_PASSWORD: mailgun-password
      COMMENTO_SMTP_FROM_ADDRESS: noreply@noted.lol
    depends_on:
      - db
  db:
    image: postgres:12.5-alpine
    environment:
      POSTGRES_DB: commento
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - commento_data_volume:/var/lib/postgresql/data

volumes:
  commento_data_volume:
```

I don't really know where to go from here. According to the reactions on that blog post, everything should work fine :) I must be doing something wrong in a dumb way!

-------------------------------

Bonus question:

I plan to run this behind a Caddy reverse proxy, but I don't think that's the issue here because the server doesn't even start up.

In any case, if I run it behind a reverse proxy (So caddy will forward traffic from `commento.mydomain.com:80` -> `127.0.0.1:8096`, should I set my `COMMENTO_ORIGIN` to `127.0.0.1:8080` or to `commento.mydomain.com`? I tried both, neither make the server start up.

**Comment by souramoo** [comment]
This is expected as described by https://github.com/souramoo/commentoplusplus/pull/89#issuecomment-1091696774

If you have any suggestions on how to fix the build process errors caused by missing binaries in the arm64 images we base ourselves on, please do open a pull request and I'd love to merge it!

There is nothing in principle stopping us from compiling this for arm other than this!

**Comment by souramoo** [comment]
Actually, exec format error suggests that the correct executable format is not present but the RPi3B+ is an arm64 device.

Please could you double check you are using the correct arm64 image rather than the amd64 image?

**Comment by sander1095** [comment]
Wow! Thanks for the ultra fast reply!

I only see `amd64` on the docker hub:  https://hub.docker.com/r/caroga/commentoplusplus/tags

How would I be able to install an `arm64` image?

**Comment by sander1095** [comment]
AFAIK I have the `amd64` image:

![image](https://user-images.githubusercontent.com/7312681/185665171-e6f576d9-8359-41d9-9f81-832cb09df0a2.png)
![image](https://user-images.githubusercontent.com/7312681/185665202-4a470094-e0c5-4ee7-9ffe-afc2383af29f.png)

**Comment by sander1095** [comment]
So, there is currently no way to run this on a pi because of missing arm64 support, right?

I have no `go` or `arm64` knowledge, but I suppose I can take a look, perhaps this weekend. I'd love to use this on my Pi!

**Comment by sander1095** [comment]
I'm looking into the base images the [Dockerfile](https://github.com/souramoo/commentoplusplus/blob/master/Dockerfile) uses, but I don't see anything that wouldn't support `arm64`.

- [golang-alpine](https://hub.docker.com/_/golang/tags?page=1&name=alpine) seems to have support for multiple `arm*`  architectures
- [node-alpine](https://hub.docker.com/_/node/tags?page=1&name=alpine) seems to have support for multiple `arm*` architectures
- [alpine](https://hub.docker.com/_/alpine/tags) seems to have support for multiple `arm*` architectures
- [gcr.io/distroless/static-debian11](gcr.io/distroless/static-debian11) seems to have support for `arm` architectures
  - I found this a bit more difficult to figure out, so I just pulled one of these images (on my pi) and inspected the image and saw:
![image](https://user-images.githubusercontent.com/7312681/185669739-81a22eb5-e62f-4151-84f7-52b5eb17ed0f.png)

I feel like I am kind of out of my depth here, apologies! :)

@Wonderfall, you commented that support should be removed for arm because of issues, perhaps you can help me out here? Especially since you created the PR for a better dockerfile?

Thanks!

**Comment by sander1095** [comment]
If I clone the repo and run `docker-compose up`, it actually DOES start up.

My first hunch is that `arm` is now actually supported! I will test a bit more now

**Comment by souramoo** [comment]
Thanks for looking into this! Yes you're right, I have updated the docker build process - please try pulling the latest one as there should be an arm64 image now on dockerhub!

**Comment by sander1095** [comment]
Hey @souramoo , I think this isnt't working yet.

If I use this docker compose file:

```
version: '3.7'

services:
  commento:
    image: caroga/commentoplusplus
    environment:
      COMMENTO_ORIGIN: 'https://commento.stenbrinke.nl'
      COMMENTO_PORT: '8080'
      COMMENTO_POSTGRES: 'postgres://postgres:postgres@db:5432/commento?sslmode=disable'
      #COMMENTO_FORBID_NEW_OWNERS: 'true' # enable this after your own registration
      COMMENTO_GZIP_STATIC: 'true'
    depends_on:
      - db
    ports:
      - 8080:8080

  db:
    image: postgres:12.5-alpine
    environment:
      POSTGRES_DB: 'commento'
      POSTGRES_USER: 'username'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - /mnt/usb_hdd/commento:/var/lib/postgresql/data
```

running `docker compose up` gives me this error:

```
[+] Running 0/2
 ⠇ db Pulling                                                                                                                                                                                              
 ⠇ commento Pulling                                                                                                                                                                                        
no matching manifest for linux/arm/v7 in the manifest list entries
```

Could you still look into this? 

Also, should another github release be required for this? I am pulling the latest images.
I still see version 1.8.7 on github and docker hub; I thought an architecture change would require `1.8.8` or 1.9.0` or something?  :)

**Comment by souramoo** [comment]
I will look into this! I think it's looking for armv7 (32 bit arm) rather than arm64

The code for commento is the same so I kept the version number constant, just a further architecture we are compiling for, but if I need to make further changes to the codebase to get it to work I will bump the version number :)

**Comment by Wonderfall** [comment]
Yes, `linux/arm/v7` is currently not supported by Commento++ Docker images. Maybe just adding it in the GitHub Actions workflow can work, if all the dependencies (images and packages) work fine with that.

**Comment by Wonderfall** [comment]
Actually, it shouldn't be the problem as the Raspberry Pi 3 is `arm64`.
Can you try the image from ghcr.io instead?

**Comment by sander1095** [comment]
Hi @Wonderfall !

I tried changing my image to that, but I get the following error.

```
Pulling commento (ghcr.io/souramoo/commentoplusplus:v1.8.7)...
v1.8.7: Pulling from souramoo/commentoplusplus
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries
```

For full disclosure, here is my dockerfile:

```
version: '3'

services:
  commento:
    image: ghcr.io/souramoo/commentoplusplus:v1.8.7
    ports:
      - 8080:8080
    environment:
      COMMENTO_ORIGIN: https://commento.stenbrinke.nl
      COMMENTO_PORT: 8080
      COMMENTO_POSTGRES: postgres://postgres:postgres@db:5432/commento?sslmode=disable
    depends_on:
      - db
    networks:
      - db_network
  db:
    image: postgres
    environment:
      POSTGRES_DB: commento
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - db_network
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data

networks:
  db_network:

volumes:
  postgres_data_volume:
```

I run raspbian lite :) Running `uname -a` (thanks to [this](https://vitux.com/get-linux-system-and-hardware-details-on-the-command-line/) site) tells me that I have `Linux raspberrypi 5.15.32-v7+ #1538 SMP Thu Mar 31 19:38:48 BST 2022 armv7l GNU/Linux`
