### ISSUE TITLE
This page isn’t working right now error with docker-compose

### ISSUE THREAD

**Issue by tempcoderr** [souramoo/commentoplusplus#142]
I have written the following docker compose file:
```
version: "3"

services:
  server:
    build: https://github.com/souramoo/commentoplusplus.git
    ports:
      - 3002:8080
    environment:
      COMMENTO_ORIGIN: http://localhost:3002
      COMMENTO_PORT: 3002
      COMMENTO_POSTGRES: postgres://postgres:testpass@db:5432/commentopp?sslmode=disable
    depends_on:
      - db
    networks:
      - db_network
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: commentopp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpass
    networks:
      - db_network
    volumes:
      - postgres_data_volume:/var/lib/postgresql2/data

networks:
  db_network:

volumes:
  postgres_data_volume:
```
When I do `docker-compose up` and open `http://localhost:3002`, it gives me `This page isn’t working right now` error. Can anyone tell me what is wrong here?
